Repository researchshare-official/frontend, pull requests merged in 2021-12, with the labels that each got.

#1 Theme thinking
  components/AppBar.tsx
  next.config.js
  pages/_app.tsx
  styles/Home.module.css
  utils/ColorModeContext.ts
  utils/Theme.ts
Labels: help wanted

#18 About
  pages/About.tsx
  public/images/hero/Screenshot_20211207_151305.png
  public/images/hero/dotted-shape.svg
  styles/About.module.css
Labels: enhancement, P4

#11 [E-REPUTATION] Login component
  .eslintrc.json
  .prettierrc.json
  .vscode/settings.json
  components/AppBar.tsx
  components/Login.tsx
  package.json
  pages/_app.tsx
  pages/api/hello.ts
  pages/index.tsx
  styles/Home.module.css
  styles/Login.module.css
  styles/globals.css
  yarn.lock
Labels: enhancement, P1

#15 [E-REPUTATION] profil summary
  components/AppBar.tsx
  components/Profile/OnePublication.tsx
  components/Profile/ProfileContent.tsx
  components/Profile/Summary.tsx
  components/Profile_labo/OnePublication.tsx
  components/Profile_labo/ProfileContent.tsx
  components/Profile_labo/Summary.tsx
  package-lock.json
  package.json
  pages/About.tsx
  pages/index.tsx
  pages/profile.tsx
  pages/profile_labo.tsx
  public/ActivityChart.png
  public/profile-picture-labo.png
  public/profile-picture.png
  styles/Home.module.css
  types/OnePublication.ts
  yarn.lock
Labels: enhancement, P1

#29 Detailed search
  components/DetailedSearch/CategoriesFilter.tsx
  components/DetailedSearch/Date.tsx
  components/DetailedSearch/IncludeFilter.tsx
  components/DetailedSearch/SideBar.tsx
  components/DetailedSearch/WhatAreYouLookingFor.tsx
  pages/detailed_search.tsx
  public/SearchPlaceHolder.png
Labels: P1

#30 Submit paper fonctionel pour forward
  components/submitPaper/getWork.tsx
  package.json
  pages/api/axios.tsx
  pages/submit-paper.tsx
  yarn.lock
Labels: P1

#19 Page template
  components/ArticlePreview.tsx
  components/HotArticlePreview.tsx
  mocking/articles.json
  mocking/hot_articles.json
  pages/index.tsx
  public/camion.jpg
  public/compose.png
  styles/Home.module.css
Labels: P3
